### ISSUE TITLE
Update example notebooks

### ISSUE THREAD

**Issue by moratodpg** [AI-for-Infrastructure-Management/imp-act#40]
After the modification of the installation process, we have to update our example notebooks. 

[Notebooks](https://github.com/AI-for-Infrastructure-Management/imp-rl-challenge/tree/main/imp_rl_challenge/policies/example_notebooks)

**Comment by DanielHettegger** [comment]
Is this still being worked on or is it resolved already?

**Comment by zieadm** [comment]
the only one needs updating is tune_heurestics.ipynb. I will provide the last version I am using tomorrow and pull the branch with the interactive baselines
.
